"""Declarative configuration for Soothe Nano (Coding CoreAgent)."""

from soothe_nano.config.constants import (
    DEFAULT_EXECUTE_TIMEOUT,
)
from soothe_nano.config.env import (
    _ENV_VAR_RE,
    SOOTHE_HOME,
    _expand_env_in_config,
    _resolve_env,
    _resolve_provider_env,
)
from soothe_nano.config.models import (
    AgentConfig,
    ConsoleLoggingConfig,
    CoreAgentMiddlewareConfig,
    DurabilityProtocolConfig,
    EmbeddingProfile,
    FileLoggingConfig,
    HttpRequestsToolsConfig,
    LLMRateLimitConfig,
    LoopToolOutputConfig,
    MCPServerConfig,
    MemUConfig,
    ModelProviderConfig,
    ModelRouter,
    ObservabilityConfig,
    PersistenceConfig,
    PlannerProtocolConfig,
    PolicyProtocolConfig,
    PostgresPoolConfig,
    ProtocolsConfig,
    RouterProfile,
    SecurityConfig,
    SqliteRuntimeConfig,
    SubagentConfig,
    ThreadLoggingConfig,
    ToolConfig,
    ToolsConfig,
    VectorStoreProviderConfig,
    VectorStoreRouter,
    WebSearchConfig,
    parse_model_specs,
)
from soothe_nano.config.settings import SootheConfig
from soothe_nano.prompts.system_templates import (
    _DEFAULT_SYSTEM_PROMPT,
    _MEDIUM_SYSTEM_PROMPT,
    _SIMPLE_SYSTEM_PROMPT,
    _TOOL_ORCHESTRATION_GUIDE,
)

NanoConfig = SootheConfig

__all__ = [
    "DEFAULT_EXECUTE_TIMEOUT",
    "SOOTHE_HOME",
    "_DEFAULT_SYSTEM_PROMPT",
    "_ENV_VAR_RE",
    "_MEDIUM_SYSTEM_PROMPT",
    "_SIMPLE_SYSTEM_PROMPT",
    "_TOOL_ORCHESTRATION_GUIDE",
    "AgentConfig",
    "CoreAgentMiddlewareConfig",
    "ConsoleLoggingConfig",
    "DurabilityProtocolConfig",
    "EmbeddingProfile",
    "FileLoggingConfig",
    "HttpRequestsToolsConfig",
    "LLMRateLimitConfig",
    "LoopToolOutputConfig",
    "MCPServerConfig",
    "MemUConfig",
    "ModelProviderConfig",
    "ModelRouter",
    "RouterProfile",
    "ObservabilityConfig",
    "PersistenceConfig",
    "PlannerProtocolConfig",
    "PolicyProtocolConfig",
    "PostgresPoolConfig",
    "ProtocolsConfig",
    "SecurityConfig",
    "SqliteRuntimeConfig",
    "SootheConfig",
    "NanoConfig",
    "SubagentConfig",
    "ThreadLoggingConfig",
    "ToolConfig",
    "ToolsConfig",
    "VectorStoreProviderConfig",
    "VectorStoreRouter",
    "WebSearchConfig",
    "parse_model_specs",
    "_resolve_env",
    "_resolve_provider_env",
    "_expand_env_in_config",
]
